In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(1)
print(x)

tensor([0.])


In [3]:
x = torch.empty(2, 3, 4, 5)
print(x)

tensor([[[[3.1950e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.1095e+27],
          [1.3566e-14, 3.3738e-12, 1.7592e+22, 1.4355e-19, 2.7530e+12],
          [7.5338e+28, 5.9288e+11, 6.7120e+22, 4.6114e+24, 2.1459e+20],
          [9.2489e-04, 1.1096e+27, 5.0825e+31, 7.5338e+28, 1.0886e+27]],

         [[1.9603e-19, 1.9432e-19, 6.9772e+22, 1.6931e+22, 4.5144e+27],
          [1.8393e+25, 1.8496e+20, 4.6114e+24, 1.7463e+25, 2.0193e-19],
          [6.7421e+22, 2.3739e+12, 2.0618e-19, 4.3988e+21, 1.8524e+28],
          [7.2714e+31, 1.8892e+31, 8.1322e+32, 2.0955e-19, 5.0833e+31]],

         [[4.9640e+28, 1.7485e+25, 2.0022e-19, 1.8888e+31, 3.2543e+33],
          [1.9690e-19, 1.9432e-19, 7.2728e+22, 1.7237e+25, 1.8888e+31],
          [2.0196e-19, 7.3471e+28, 5.1931e-11, 3.8235e+30, 8.9773e-33],
          [1.3563e-19, 2.0110e-19, 7.5555e+31, 5.0778e+31, 1.1835e+22]]],


        [[[1.7751e+28, 1.8524e+28, 2.0283e-19, 4.3059e+21, 1.3556e-19],
          [1.8037e+28, 2.1040e-19, 7.5555e+31, 5.0778e+3

In [4]:
x = torch.rand(2, 3)
print(x)

tensor([[0.6731, 0.0572, 0.5418],
        [0.4676, 0.0607, 0.1579]])


In [5]:
x = torch.rand(1)
print(x)

tensor([0.5893])


In [6]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.ones(2, 3)
print (x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x.dtype

torch.float32

In [9]:
x = torch.ones(2, 3, dtype=torch.int)
x.dtype

torch.int32

In [10]:
print(x.size())

torch.Size([2, 3])


In [11]:
x = torch.tensor([2.4, 5.2])
print(x)

tensor([2.4000, 5.2000])


In [12]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x + y
z = torch.add(x, y)
print(z)

tensor([[0.0740, 0.3722],
        [0.8453, 0.7399]])
tensor([[0.8189, 0.2334],
        [0.5984, 0.6728]])
tensor([[0.8929, 0.6056],
        [1.4437, 1.4128]])


In [13]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.add_(x)   # In pytorch every function with trailing underscore will do inplace functionality
print(y)

tensor([[0.5326, 0.0436],
        [0.3156, 0.1729]])
tensor([[0.4036, 0.7184],
        [0.3696, 0.7883]])
tensor([[0.9362, 0.7620],
        [0.6851, 0.9611]])


In [14]:
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.4036, -0.7184],
        [-0.3696, -0.7883]])


In [15]:
z = torch.mul(x, y)
print(z)

tensor([[0.4986, 0.0332],
        [0.2162, 0.1661]])


In [16]:
z = torch.div(x, y)
print(z)

tensor([[0.5689, 0.0572],
        [0.4606, 0.1799]])


In [17]:
x = torch.rand(5, 3)
print(x)
print(x[1, 1].item())

tensor([[0.5159, 0.5179, 0.3201],
        [0.8008, 0.6121, 0.3343],
        [0.6981, 0.7885, 0.1291],
        [0.9500, 0.9442, 0.7179],
        [0.7966, 0.3559, 0.8594]])
0.6121405959129333


In [18]:
print(x[:, 0:2])

tensor([[0.5159, 0.5179],
        [0.8008, 0.6121],
        [0.6981, 0.7885],
        [0.9500, 0.9442],
        [0.7966, 0.3559]])


In [19]:
x = torch.rand(4, 4)
print(x)

y = x.view(16)
print(y)

tensor([[0.6508, 0.1485, 0.4081, 0.4222],
        [0.6390, 0.0735, 0.5224, 0.9513],
        [0.5375, 0.0581, 0.5479, 0.3529],
        [0.4482, 0.8887, 0.6463, 0.0032]])
tensor([0.6508, 0.1485, 0.4081, 0.4222, 0.6390, 0.0735, 0.5224, 0.9513, 0.5375,
        0.0581, 0.5479, 0.3529, 0.4482, 0.8887, 0.6463, 0.0032])


In [20]:
y = x.view(-1, 8)
print(y)

tensor([[0.6508, 0.1485, 0.4081, 0.4222, 0.6390, 0.0735, 0.5224, 0.9513],
        [0.5375, 0.0581, 0.5479, 0.3529, 0.4482, 0.8887, 0.6463, 0.0032]])


In [21]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [22]:
a.add_(1)
print(a)
print(b)    # since we are using CPU memory, if we modify the tensor, the numpy array is also modified and vice versa

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
