In [1]:
import torch

In [3]:
x = torch.rand(3, requires_grad=True)
print(x)

tensor([0.8127, 0.6963, 0.6832], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([2.8127, 2.6963, 2.6832], grad_fn=<AddBackward0>)


In [11]:
z = y * y * 2
print(z)

tensor([15.8222, 14.5405, 14.3992], grad_fn=<MulBackward0>)


In [10]:
z = z.mean()
print(z)

tensor(14.9206, grad_fn=<MeanBackward0>)


In [13]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)    # dz/dx
print(x.grad)

tensor([ 4.8753, 14.3805,  3.5883])


In [18]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad(): 

x = torch.rand(3, requires_grad=True)
print(x)

# x.requires_grad_(False)
# print(x)

# y = x.detach()
# print(y)

with torch.no_grad():
    y = x + 2
    print(y)
y = x + 2
print(y)

tensor([0.8583, 0.8661, 0.1703], requires_grad=True)
tensor([2.8583, 2.8661, 2.1703])
tensor([2.8583, 2.8661, 2.1703], grad_fn=<AddBackward0>)


In [28]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(4):
    model_output = (weights * 3).sum()
    
    print(model_output)

    model_output.backward()

    print(weights.grad)

    # weights.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([6., 6., 6., 6.])
tensor(12., grad_fn=<SumBackward0>)
tensor([9., 9., 9., 9.])
tensor(12., grad_fn=<SumBackward0>)
tensor([12., 12., 12., 12.])


In [30]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0)
c = a * b
print(a)
print(b)
print(c)

tensor(2., requires_grad=True)
tensor(3.)
tensor(6., grad_fn=<MulBackward0>)


In [31]:
c.backward()

In [34]:
print(a.grad)

tensor(3.)
