In [1]:
import torch
import torch.nn as nn
import numpy as np

## SoftMax

In [3]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis = 0)

In [4]:
x = np.array([2.0, 1.0, 0.1])
output = softmax(x)
print('softmax numpy: ', output)

softmax numpy:  [0.65900114 0.24243297 0.09856589]


In [2]:
x = torch.tensor([2.0, 1.0, 0.1])
output = torch.softmax(x, dim=0)
print(output)

tensor([0.6590, 0.2424, 0.0986])


## Cross Entropy

In [7]:
def cross_entropy(actual, predicted):
    loss = -np.sum(actual * np.log(predicted))
    return loss

In [8]:
Y = np.array([1, 0, 0])

Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])

l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)

print(f'loss1 numpy: {l1:.4f}')
print(f'loss2 numpy: {l2:.4f}')

loss1 numpy: 0.3567
loss2 numpy: 2.3026


In [9]:
loss = nn.CrossEntropyLoss()

In [13]:
Y = torch.tensor([2, 0, 1])
# n_samples x n_classes = 3 * 3

Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])
Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 3.0, 0.1]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(f'loss1: {l1.item()}')
print(f'loss2: {l2.item()}')

loss1: 0.3018244206905365
loss2: 1.6241613626480103


In [14]:
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)
print(predictions1)
print(predictions2)

tensor([2, 0, 1])
tensor([0, 2, 1])
